### ISSUE TITLE
Font Awesome Take Down Request

### ISSUE THREAD

**Issue by alexpoiry** [dimaslanjaka/Web-Manajemen#73]
Hello,

I am the head of security for Font Awesome. This repository contains a complete collection of all our Font Awesome Pro assets (https://github.com/dimaslanjaka/Web-Manajemen/tree/master/svgs). These cannot be made available for free via a public repository. I would like to politely request that you remove these items from your repo and all branches.

I assume you didn't intend to violate our license and so would like to work with you and give you the time and opportunity to correct these issues before filing a DMCA request with GitHub. Please respond to this issue so that we can work to remedy this issue.

**Comment by dimaslanjaka** [comment]
okay sir, i will take down it

**Comment by alexpoiry** [comment]
Thank you for your quick response.  Closing issue.
